baseURL = "https://myblog-45j.pages.dev/"
languageCode = "zh-cn"
title = "Good Luck"
theme = "PaperMod"

# URL 配置
relativeURLs = false
canonifyURLs = false

# 菜单
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

# 主题参数
[params]
  description = "我的博客"
  author = "xiaoyu"
  defaultTheme = "auto"
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowToc = true


# 输出配置
[outputs]
  home = ["HTML", "RSS"]